/** Known input column headers — optional; mapped when present (order-independent). */
export const INPUT_COLUMNS = [
  'Trpsätt',
  'Kundnr',
  'Namn',
  'Adress',
  'Postnr',
  'Ort',
  'Information',
  'C½pal',
  '½PL F',
  'CP',
  'EUR',
  'EUR F',
  'FP F',
  'PP',
  'RB',
  'SRS',
  'SRS F',
  'Vikt Kg Fryst',
  'Vikt Kg Kylt/Torrt',
  'Lossningskod',
  'fraktsedelnummer',
] as const

/** Output column headers in exact export order. */
export const OUTPUT_COLUMNS = [
  'Kundnr',
  'Datum',
  'Märkning',
  'Fraktsedel',
  'Littera',
  'Kundkontakt',
  'Tjänst',
  'Tjänst antal',
  'Term. Namn',
  'Term. Adress',
  'Term. Postnr',
  'Term. Postort',
  'Mott. Nr',
  'Mott. Namn',
  'Mott. Adress',
  'Mott. Postnr',
  'Mott. Postort',
  'Godsslag Temp',
  'Godsslag',
  'Kolli antal',
  'Kolli vikt',
  'Pall pallplats',
  'Chaufförsinstruktion',
  'Telefonnr',
  'Inbärning',
  'Startid',
  'Sluttid',
  'Resurs',
  'Gods antal1',
  'Gods sort1',
] as const

export type InputColumn = (typeof INPUT_COLUMNS)[number]
export type OutputColumn = (typeof OUTPUT_COLUMNS)[number]
